protocol = "proxr-serial"
doc = ""
traits = ["is-daemon"]

[links]
source = "https://github.com/yaq-project/yaqd-proxr"
bugtracker = "https://github.com/yaq-project/yaqd-proxr/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-proxr"

[config]

[state]

[messages]

